import { Ciudad } from '@/types/ciudad';

export const CIUDADES: Ciudad[] = [
  { slug: 'madrid', nombre: 'Madrid', comunidad: 'Comunidad de Madrid', poblacion: 3400000, lat: 40.4168, lng: -3.7038, zonas: ['Centro', 'Chamberí', 'Salamanca', 'Retiro', 'Arganzuela', 'Carabanchel'], contenidoLocal: {
    'limpieza-comunidades': { intro: 'Madrid es la ciudad con mayor número de comunidades de propietarios de España.', datoRelevante: 'El convenio colectivo de limpieza de la Comunidad de Madrid establece la subrogación obligatoria.', precioContexto: 'Un portal con escalera ronda los 250-450€/mes.' },
    'mantenimiento-comunidades': { intro: 'Madrid concentra un parque de edificios muy heterogéneo, desde fincas de principios del siglo XX en Chamberí y Salamanca hasta promociones de los años 70 en Carabanchel, lo que exige planes de mantenimiento adaptados a cada antigüedad. Muchas comunidades combinan instalaciones originales con reformas parciales, lo que complica la gestión preventiva.', datoRelevante: 'La ordenanza municipal de Madrid obliga a pasar la Inspección Técnica de Edificios (ITE) a los inmuebles de más de 30 años y a renovarla cada 10 años.', precioContexto: 'El mantenimiento integral en Madrid se sitúa en la parte alta de la media nacional, sobre todo en edificios históricos del centro con instalaciones más costosas de conservar.' },
    'conserjeria-comunidades': { intro: 'En distritos como Salamanca, Chamberí o Retiro la conserjería sigue siendo un servicio muy valorado, ligado tanto a la seguridad como a la imagen del edificio. En las nuevas promociones de la periferia crece la demanda de conserjería polivalente combinada con control de accesos.', datoRelevante: 'El convenio colectivo de conserjes de fincas urbanas de Madrid regula turnos, categorías profesionales y la subrogación obligatoria al cambiar de empresa.', precioContexto: 'Los costes laborales del sector en Madrid elevan el precio de la conserjería por encima de la media nacional, sobre todo en turnos completos de 8 horas.' },
    'reformas-comunidades': { intro: 'Buena parte del parque residencial de Madrid supera los 40 años, lo que dispara la demanda de reformas de fachada, cubierta e instalaciones en distritos como Tetuán, Carabanchel o Usera. En el distrito Centro, muchas reformas de fachada están además condicionadas por la protección patrimonial de los edificios.', datoRelevante: 'El plan MAD-RE del Ayuntamiento de Madrid subvenciona reformas de rehabilitación energética y accesibilidad en comunidades de propietarios.', precioContexto: 'Los presupuestos de reforma en Madrid suelen superar la media nacional por el coste de licencias, andamios y mano de obra especializada en el centro urbano.' },
    'jardineria-comunidades': { intro: 'Las urbanizaciones de la periferia (Pozuelo, Las Rozas, Boadilla) concentran buena parte de las comunidades con zonas ajardinadas extensas, mientras que en el centro urbano el servicio se limita a jardineras y patios interiores. El clima continental, con veranos muy secos e inviernos fríos, exige planes de riego y poda muy estacionales.', datoRelevante: 'El Canal de Isabel II puede imponer restricciones de riego en periodos de sequía que afectan directamente a las comunidades con jardín.', precioContexto: 'El coste de jardinería en Madrid varía mucho entre el centro urbano y las urbanizaciones periféricas, donde las parcelas más grandes elevan la factura mensual.' },
    'mantenimiento-piscinas': { intro: 'Las urbanizaciones del extrarradio de Madrid, con veranos calurosos y secos, concentran gran parte de la demanda de mantenimiento de piscinas comunitarias, con temporada de baño que suele abrir a mediados de mayo y cerrar en septiembre. Las fuertes oscilaciones térmicas entre el día y la noche obligan a vigilar de cerca el tratamiento químico del agua.', datoRelevante: 'La normativa de la Comunidad de Madrid sobre piscinas de uso colectivo exige registros diarios de cloro y pH durante toda la temporada de baño.', precioContexto: 'Los precios de mantenimiento de piscinas en Madrid se mantienen en línea con la media nacional, aunque la contratación de socorristas en temporada alta encarece el servicio integral.' },
  } },
  { slug: 'barcelona', nombre: 'Barcelona', comunidad: 'Cataluña', poblacion: 1660000, lat: 41.3851, lng: 2.1734, zonas: ['Eixample', 'Gràcia', 'Sarrià-Sant Gervasi', 'Sant Martí'], contenidoLocal: {
    'limpieza-comunidades': { intro: 'Barcelona cuenta con más de 70.000 comunidades de propietarios.', datoRelevante: 'El convenio catalán establece condiciones específicas de subrogación.', precioContexto: 'Precios un 10-15% superiores a la media nacional.' },
    'mantenimiento-comunidades': { intro: 'Barcelona combina fincas centenarias del Eixample y Ciutat Vella con edificios de posguerra en Nou Barris o Sant Andreu, lo que obliga a planes de mantenimiento muy distintos según el barrio. La proximidad al mar acelera el desgaste de fachadas, carpinterías metálicas e instalaciones comunes.', datoRelevante: 'La Inspecció Tècnica de l\'Edifici (ITE) es obligatoria en Cataluña para inmuebles de más de 45 años, y debe renovarse cada 10 años.', precioContexto: 'El mantenimiento integral en Barcelona suele costar por encima de la media nacional, en parte por el mayor coste de materiales y mano de obra especializada en rehabilitación.' },
    'conserjeria-comunidades': { intro: 'En zonas como Pedralbes, Sarrià-Sant Gervasi o el Eixample la conserjería forma parte del estándar de muchas fincas, mientras que en barrios más densos como Ciutat Vella se combina con control de accesos reforzado. La alta rotación de alquiler turístico en algunas zonas también incrementa la necesidad de conserjes que gestionen entradas y paquetería.', datoRelevante: 'El convenio de finques urbanes de Catalunya regula categorías, turnos y la subrogación obligatoria del personal de conserjería al cambiar de empresa.', precioContexto: 'Los costes laborales en Barcelona sitúan el precio de la conserjería un 10-15% por encima de la media nacional, en línea con lo que ocurre con la limpieza.' },
    'reformas-comunidades': { intro: 'El Eixample y Ciutat Vella concentran edificios con elementos protegidos —balcones, fachadas modernistas, portales— lo que obliga a tramitar permisos específicos del Ajuntament antes de reformar. Fuera del centro histórico, barrios como Nou Barris u Horta-Guinardó demandan más reformas de instalaciones que de fachada.', datoRelevante: 'El Pla de Millora Energètica de Barcelona (PMEB) subvenciona reformas de rehabilitación energética en comunidades de propietarios.', precioContexto: 'Las reformas de fachada en zonas protegidas de Barcelona pueden costar más que la media nacional por las restricciones patrimoniales y los materiales exigidos.' },
    'jardineria-comunidades': { intro: 'El tejido urbano denso de Barcelona deja poco espacio para jardines comunitarios salvo en zonas como Pedralbes o Sarrià, donde las fincas con parcela propia sí disponen de zonas verdes amplias. El clima mediterráneo permite un calendario de mantenimiento más largo que en el interior peninsular, pero con veranos muy secos.', datoRelevante: 'La Agència Catalana de l\'Aigua puede activar restricciones de riego en episodios de sequía que limitan el mantenimiento de jardines comunitarios.', precioContexto: 'El servicio de jardinería en Barcelona es más caro que la media nacional en las zonas con parcelas grandes, aunque escaso en el resto de la ciudad por la falta de superficie ajardinada.' },
    'mantenimiento-piscinas': { intro: 'El clima mediterráneo de Barcelona permite una temporada de baño más larga que en el interior, con piscinas comunitarias que a menudo abren en abril y cierran en octubre. Las urbanizaciones de la zona alta y el área metropolitana concentran la mayor parte de la demanda de este servicio.', datoRelevante: 'El Decret 95/2000 regula las piscinas de uso colectivo en Cataluña y exige controles analíticos periódicos del agua durante toda la temporada.', precioContexto: 'Los precios de mantenimiento de piscinas en Barcelona se sitúan ligeramente por encima de la media nacional, en línea con el resto de servicios para comunidades en la ciudad.' },
  } },
  { slug: 'valencia', nombre: 'Valencia', comunidad: 'Comunitat Valenciana', poblacion: 800000, lat: 39.4699, lng: -0.3763, zonas: ["Ciutat Vella", "L'Eixample", 'Extramurs'], contenidoLocal: {
    'limpieza-comunidades': { intro: 'Valencia cuenta con un parque inmobiliario muy diverso.', datoRelevante: 'El convenio valenciano regula subrogación y jornada.', precioContexto: 'Precios 15-20% inferiores a Madrid y Barcelona.' },
    'mantenimiento-comunidades': { intro: 'Valencia combina edificios de los años 60-70 en Extramurs o Benimaclet con construcciones más recientes en zonas como Nuevo Centro, lo que exige planes de mantenimiento adaptados a distintas antigüedades y materiales. La humedad ambiental propia del clima mediterráneo acelera el desgaste de instalaciones metálicas y fachadas.', datoRelevante: 'En la Comunitat Valenciana el Informe de Evaluación de Edificios (IEE) es obligatorio para inmuebles de más de 50 años.', precioContexto: 'El coste del mantenimiento integral en Valencia suele ser más asequible que en Madrid o Barcelona, en línea con el menor coste de vida de la ciudad.' },
    'conserjeria-comunidades': { intro: 'En el Eixample valenciano y zonas como Ciutat Vella la conserjería sigue siendo habitual en fincas de cierto tamaño, mientras que en las nuevas promociones de Benimaclet o Patraix se opta cada vez más por conserjería polivalente combinada con mantenimiento básico. El turismo en zonas próximas a la playa también incrementa la necesidad de control de accesos en temporada alta.', datoRelevante: 'El convenio de fincas urbanas de la Comunitat Valenciana regula la subrogación de conserjes y las categorías profesionales del sector.', precioContexto: 'El coste laboral más contenido en Valencia hace que la conserjería sea, en general, entre un 15% y un 20% más económica que en Madrid o Barcelona.' },
    'reformas-comunidades': { intro: 'La proximidad al Mediterráneo y al cauce del Turia hace que muchas comunidades de Valencia necesiten reformas relacionadas con humedades e impermeabilización de cubiertas, además de las típicas actuaciones en fachada. El Ayuntamiento impulsa desde hace años programas de rehabilitación en barrios como Russafa o el Cabanyal.', datoRelevante: 'Las Áreas de Regeneración y Renovación Urbana (ARRU) de Valencia ofrecen ayudas específicas para rehabilitar fachadas y cubiertas en comunidades de propietarios.', precioContexto: 'Las reformas en Valencia suelen tener presupuestos más ajustados que en Madrid o Barcelona, aunque el precio se eleva en zonas con edificios protegidos como el Cabanyal.' },
    'jardineria-comunidades': { intro: 'El clima suave de Valencia, con inviernos poco fríos, permite un calendario de jardinería más largo que en el interior peninsular, sobre todo en urbanizaciones de la periferia con zonas verdes amplias. La cercanía a la huerta valenciana también facilita el acceso a plantas y sustratos adaptados a la zona.', datoRelevante: 'La Confederación Hidrográfica del Júcar puede limitar el riego de zonas verdes comunitarias en episodios de escasez de agua.', precioContexto: 'El servicio de jardinería en Valencia suele ser más económico que en Madrid o Barcelona, en línea con el menor coste general de los servicios para comunidades en la ciudad.' },
    'mantenimiento-piscinas': { intro: 'El clima cálido y húmedo de Valencia alarga la temporada de baño de las piscinas comunitarias, que en muchas urbanizaciones abren ya en marzo y no cierran hasta octubre. Esto exige un seguimiento más constante del tratamiento del agua que en zonas de interior con temporadas más cortas.', datoRelevante: 'La normativa autonómica valenciana sobre piscinas de uso colectivo exige analíticas periódicas de agua y registro de incidencias durante toda la temporada de apertura.', precioContexto: 'Los precios de mantenimiento de piscinas en Valencia son similares o ligeramente inferiores a la media nacional, gracias al menor coste de mano de obra especializada.' },
  } },
  { slug: 'sevilla', nombre: 'Sevilla', comunidad: 'Andalucía', poblacion: 685000, lat: 37.3891, lng: -5.9845, zonas: ['Triana', 'Nervión', 'Macarena'], contenidoLocal: {} },
  { slug: 'malaga', nombre: 'Málaga', comunidad: 'Andalucía', poblacion: 580000, lat: 36.7213, lng: -4.4214, zonas: ['Centro', 'Teatinos', 'El Palo'], contenidoLocal: {} },
  { slug: 'zaragoza', nombre: 'Zaragoza', comunidad: 'Aragón', poblacion: 675000, lat: 41.6488, lng: -0.8891, zonas: ['Centro', 'Delicias', 'Actur'], contenidoLocal: {} },
  { slug: 'bilbao', nombre: 'Bilbao', comunidad: 'País Vasco', poblacion: 347000, lat: 43.2630, lng: -2.9350, zonas: ['Abando', 'Deusto', 'Indautxu'], contenidoLocal: {} },
  { slug: 'alicante', nombre: 'Alicante', comunidad: 'Comunitat Valenciana', poblacion: 337000, lat: 38.3452, lng: -0.4810, zonas: ['Centro', 'Playa de San Juan'], contenidoLocal: {} },
  { slug: 'murcia', nombre: 'Murcia', comunidad: 'Región de Murcia', poblacion: 460000, lat: 37.9922, lng: -1.1307, zonas: ['Centro', 'El Carmen'], contenidoLocal: {} },
  { slug: 'palma-de-mallorca', nombre: 'Palma de Mallorca', comunidad: 'Islas Baleares', poblacion: 420000, lat: 39.5696, lng: 2.6502, zonas: ['Centro', 'Santa Catalina'], contenidoLocal: {} },
  { slug: 'las-palmas', nombre: 'Las Palmas de Gran Canaria', comunidad: 'Canarias', poblacion: 380000, lat: 28.1235, lng: -15.4363, zonas: ['Vegueta', 'Triana'], contenidoLocal: {} },
  { slug: 'valladolid', nombre: 'Valladolid', comunidad: 'Castilla y León', poblacion: 300000, lat: 41.6523, lng: -4.7245, zonas: ['Centro', 'Parquesol'], contenidoLocal: {} },
  { slug: 'cordoba', nombre: 'Córdoba', comunidad: 'Andalucía', poblacion: 325000, lat: 37.8882, lng: -4.7794, zonas: ['Centro', 'Levante'], contenidoLocal: {} },
  { slug: 'granada', nombre: 'Granada', comunidad: 'Andalucía', poblacion: 232000, lat: 37.1773, lng: -3.5986, zonas: ['Centro', 'Zaidín', 'Albaicín'], contenidoLocal: {} },
];

export function getCiudad(slug: string) { return CIUDADES.find((c) => c.slug === slug); }
export function getCiudadSlugs() { return CIUDADES.map((c) => c.slug); }
