import { Ciudad } from '@/types/ciudad';

export const CIUDADES: Ciudad[] = [
  {
    slug: 'madrid', nombre: 'Madrid', comunidad: 'Comunidad de Madrid', poblacion: 3400000, lat: 40.4168, lng: -3.7038,
    zonas: ['Centro', 'Chamberí', 'Salamanca', 'Retiro', 'Arganzuela', 'Carabanchel', 'Vallecas', 'Hortaleza', 'Fuencarral', 'Moncloa', 'Latina', 'Usera'],
    contenidoLocal: {
      'limpieza-comunidades': { intro: 'Madrid es la ciudad con mayor número de comunidades de propietarios de España, con más de 160.000 edificios residenciales. La alta densidad urbana y el constante flujo de personas hacen imprescindible un servicio de limpieza profesional y frecuente en portales, escaleras, garajes y zonas comunes.', datoRelevante: 'El convenio colectivo de limpieza de edificios y locales de la Comunidad de Madrid establece las condiciones laborales y la subrogación obligatoria del personal.', precioContexto: 'Los precios en Madrid se sitúan en la media-alta nacional. Un portal con escalera de edificio medio ronda los 250-450€/mes con limpieza 3 veces por semana.' },
      'mantenimiento-comunidades': { intro: 'El parque inmobiliario de Madrid incluye desde edificios históricos en el centro hasta urbanizaciones modernas en los ensanches. Cada tipo de edificio requiere un plan de mantenimiento adaptado a su antigüedad y características.', datoRelevante: 'La ITE (Inspección Técnica de Edificios) es obligatoria en Madrid para edificios de más de 30 años, según la Ordenanza de Conservación, Rehabilitación y Estado Ruinoso de las Edificaciones.', precioContexto: 'El mantenimiento integral en Madrid oscila entre 600€ y 2.500€/mes para comunidades de tamaño medio.' },
      'conserjeria-comunidades': { intro: 'Madrid concentra la mayor demanda de servicios de conserjería en España. Desde edificios del barrio de Salamanca con portero tradicional hasta urbanizaciones en la periferia con conserje polivalente.', datoRelevante: 'El sector de conserjería en Madrid emplea a más de 15.000 profesionales. El convenio colectivo de porteros, conserjes, limpiadores y actividades diversas establece las condiciones salariales.', precioContexto: 'Un conserje a jornada completa en Madrid cuesta entre 1.300€ y 1.900€/mes según la zona y las funciones.' },
      'reformas-comunidades': { intro: 'Madrid cuenta con miles de edificios que necesitan reformas de fachada, rehabilitación energética y eliminación de barreras arquitectónicas. El Ayuntamiento ofrece programas de ayudas para la rehabilitación de edificios en el centro histórico.', datoRelevante: 'El Plan MAD-RE del Ayuntamiento de Madrid ofrece subvenciones para rehabilitación de edificios, especialmente en distritos como Centro, Puente de Vallecas, Usera y Villaverde.', precioContexto: 'Las reformas de fachada en Madrid oscilan entre 50€ y 120€/m² dependiendo del tipo de intervención y la dificultad de acceso.' },
      'jardineria-comunidades': { intro: 'Las urbanizaciones del norte y oeste de Madrid (Pozuelo, Boadilla, Las Rozas, Majadahonda) cuentan con amplias zonas ajardinadas que requieren mantenimiento profesional durante todo el año.', datoRelevante: 'El clima continental de Madrid, con veranos muy secos e inviernos fríos, exige una selección cuidadosa de especies vegetales y un sistema de riego eficiente.', precioContexto: 'El mantenimiento de jardines en urbanizaciones de Madrid oscila entre 300€ y 1.200€/mes dependiendo de la superficie.' },
      'mantenimiento-piscinas': { intro: 'Madrid es una de las provincias con más piscinas comunitarias de España. La temporada de baño suele abrirse en junio y cerrarse a mediados de septiembre.', datoRelevante: 'La Comunidad de Madrid exige socorrista titulado en piscinas comunitarias con capacidad superior a 20 bañistas. El Decreto 80/1998 regula las condiciones higiénico-sanitarias.', precioContexto: 'El mantenimiento integral de piscina + socorrista en temporada cuesta entre 1.500€ y 3.500€/mes en Madrid.' },
    },
  },
  {
    slug: 'barcelona', nombre: 'Barcelona', comunidad: 'Cataluña', poblacion: 1660000, lat: 41.3851, lng: 2.1734,
    zonas: ['Eixample', 'Gràcia', 'Sarrià-Sant Gervasi', 'Sant Martí', 'Sants-Montjuïc', 'Les Corts', 'Horta-Guinardó', 'Ciutat Vella', 'Nou Barris', 'Sant Andreu'],
    contenidoLocal: {
      'limpieza-comunidades': { intro: 'Barcelona cuenta con más de 70.000 comunidades de propietarios, desde fincas históricas del Eixample hasta edificios modernos del Poblenou. El clima mediterráneo y la cercanía al mar aceleran el desgaste de las zonas comunes, haciendo imprescindible un servicio de limpieza profesional.', datoRelevante: 'El convenio colectivo de limpieza de edificios y locales de Catalunya establece condiciones específicas para la subrogación de personal y los salarios del sector.', precioContexto: 'Los precios en Barcelona tienden a ser un 10-15% superiores a la media nacional debido al coste de vida y los convenios autonómicos.' },
      'mantenimiento-comunidades': { intro: 'El parque inmobiliario de Barcelona incluye edificios con más de 100 años de antigüedad que requieren un mantenimiento preventivo especializado, especialmente en el Eixample, Ciutat Vella y Gràcia.', datoRelevante: 'La ITE es obligatoria en Barcelona para edificios de más de 45 años. El Ajuntament ofrece ayudas para la rehabilitación a través del programa de ayudas a la rehabilitación.', precioContexto: 'El mantenimiento integral en Barcelona oscila entre 800€ y 3.000€/mes dependiendo del tamaño y antigüedad del edificio.' },
      'conserjeria-comunidades': { intro: 'Barcelona tiene una larga tradición de porterías, especialmente en las fincas del Eixample y Sarrià. La evolución del sector ha llevado a la profesionalización del servicio con conserjes polivalentes.', datoRelevante: 'El convenio colectivo de porteros y conserjes de fincas urbanas de Barcelona es uno de los más completos de España en cuanto a funciones y categorías profesionales.', precioContexto: 'Un conserje a jornada completa en Barcelona cuesta entre 1.400€ y 2.000€/mes, ligeramente por encima de la media nacional.' },
      'reformas-comunidades': { intro: 'Barcelona afronta un importante reto de rehabilitación del parque inmobiliario, con miles de fincas del Eixample y Ciutat Vella que necesitan intervenciones en fachadas, cubiertas e instalaciones.', datoRelevante: 'El Pla de Barris de Barcelona y las ayudas del Consorci de l\'Habitatge ofrecen financiación para la rehabilitación de edificios, especialmente en barrios con necesidades especiales.', precioContexto: 'Las reformas de fachada en Barcelona oscilan entre 55€ y 130€/m². Los costes son algo superiores a la media por la complejidad de las fincas antiguas del Eixample.' },
      'jardineria-comunidades': { intro: 'Las comunidades con jardín en Barcelona se concentran en distritos como Sarrià-Sant Gervasi, Les Corts, Pedralbes y las urbanizaciones del área metropolitana como Sant Cugat, Castelldefels o Gavà.', datoRelevante: 'El clima mediterráneo de Barcelona permite mantener jardines verdes durante gran parte del año, pero las restricciones de agua durante episodios de sequía obligan a planificar riegos eficientes.', precioContexto: 'El mantenimiento de jardines comunitarios en Barcelona parte de los 250€/mes para jardines pequeños y puede superar los 1.000€/mes en urbanizaciones grandes.' },
      'mantenimiento-piscinas': { intro: 'Pese a ser una ciudad costera, Barcelona cuenta con miles de piscinas comunitarias, especialmente en urbanizaciones del área metropolitana y comunidades del Eixample y Sant Martí.', datoRelevante: 'La normativa catalana de piscinas (Decret 95/2000) regula las condiciones sanitarias y de seguridad. El socorrismo es obligatorio en piscinas comunitarias con aforo superior a un número determinado de bañistas.', precioContexto: 'El mantenimiento integral de piscina comunitaria en Barcelona oscila entre 1.200€ y 3.000€/mes en temporada, incluyendo socorrista.' },
    },
  },
  {
    slug: 'valencia', nombre: 'Valencia', comunidad: 'Comunitat Valenciana', poblacion: 800000, lat: 39.4699, lng: -0.3763,
    zonas: ['Ciutat Vella', "L'Eixample", 'Extramurs', 'Campanar', 'Benimaclet', 'Rascanya', 'Poblats Marítims', 'Quatre Carreres', 'Patraix'],
    contenidoLocal: {
      'limpieza-comunidades': { intro: 'Valencia es la tercera ciudad de España y cuenta con un parque inmobiliario muy diverso, desde el casco histórico hasta los ensanches modernos. El clima cálido y húmedo favorece la acumulación de polvo y requiere una frecuencia de limpieza alta.', datoRelevante: 'El convenio colectivo de limpieza de edificios y locales de la Comunitat Valenciana establece las condiciones de subrogación y jornada laboral.', precioContexto: 'Los precios de limpieza de comunidades en Valencia son un 15-20% inferiores a Madrid y Barcelona. Un portal con escalera ronda los 180-350€/mes.' },
      'mantenimiento-comunidades': { intro: 'El mantenimiento de comunidades en Valencia tiene la particularidad de que muchos edificios del centro histórico requieren cuidados especiales por su antigüedad y los efectos de la humedad mediterránea.', datoRelevante: 'La ITE es obligatoria en la Comunitat Valenciana para edificios de más de 50 años. Las recientes DANA han puesto de manifiesto la importancia del mantenimiento preventivo.', precioContexto: 'El mantenimiento integral en Valencia oscila entre 400€ y 2.000€/mes, con precios más competitivos que en Madrid o Barcelona.' },
      'conserjeria-comunidades': { intro: 'La demanda de conserjería en Valencia ha crecido significativamente en los últimos años, especialmente en urbanizaciones de la periferia y en edificios del Eixample.', datoRelevante: 'El convenio colectivo de porteros y conserjes de fincas urbanas de Valencia establece las categorías profesionales y salarios del sector.', precioContexto: 'Un conserje a jornada completa en Valencia cuesta entre 1.100€ y 1.600€/mes, significativamente inferior a Madrid y Barcelona.' },
      'reformas-comunidades': { intro: 'Valencia tiene un importante parque de edificios que necesitan rehabilitación, tanto en el casco histórico como en los barrios del ensanche. Las ayudas europeas Next Generation han impulsado las reformas de eficiencia energética.', datoRelevante: 'El IVACE ofrece ayudas para la rehabilitación energética de edificios en la Comunitat Valenciana, con financiación de hasta el 80% en algunos casos.', precioContexto: 'Las reformas de fachada en Valencia oscilan entre 35€ y 100€/m², con precios más accesibles que en las grandes capitales.' },
      'jardineria-comunidades': { intro: 'El clima de Valencia permite jardines verdes durante todo el año, pero las temperaturas extremas del verano exigen sistemas de riego eficientes y especies adaptadas al mediterráneo.', datoRelevante: 'Las restricciones de agua son frecuentes en la Comunitat Valenciana durante el verano, lo que obliga a planificar jardines con xerojardinería y riego por goteo.', precioContexto: 'El mantenimiento de jardines comunitarios en Valencia parte de los 180€/mes y puede alcanzar los 800€/mes en urbanizaciones grandes.' },
      'mantenimiento-piscinas': { intro: 'Valencia tiene una de las temporadas de piscina más largas de España, pudiendo extenderse de mayo a octubre. Esto implica más meses de mantenimiento y mayor coste anual.', datoRelevante: 'La normativa de la Comunitat Valenciana sobre piscinas de uso colectivo exige socorrista y análisis de agua regulares durante toda la temporada de baño.', precioContexto: 'El mantenimiento de piscina comunitaria en Valencia oscila entre 1.000€ y 2.500€/mes en temporada, con la ventaja de una temporada larga que permite amortizar mejor la inversión.' },
    },
  },
  { slug: 'sevilla', nombre: 'Sevilla', comunidad: 'Andalucía', poblacion: 685000, lat: 37.3891, lng: -5.9845, zonas: ['Triana', 'Nervión', 'Macarena', 'Los Remedios', 'Cerro Amate', 'Este-Alcosa-Torreblanca', 'San Pablo-Santa Justa'], contenidoLocal: {} },
  { slug: 'malaga', nombre: 'Málaga', comunidad: 'Andalucía', poblacion: 580000, lat: 36.7213, lng: -4.4214, zonas: ['Centro', 'Carretera de Cádiz', 'Cruz de Humilladero', 'Teatinos', 'El Palo', 'Huelin', 'Churriana'], contenidoLocal: {} },
  { slug: 'zaragoza', nombre: 'Zaragoza', comunidad: 'Aragón', poblacion: 675000, lat: 41.6488, lng: -0.8891, zonas: ['Centro', 'Delicias', 'Universidad', 'San José', 'Las Fuentes', 'Actur', 'Oliver-Valdefierro'], contenidoLocal: {} },
  { slug: 'bilbao', nombre: 'Bilbao', comunidad: 'País Vasco', poblacion: 347000, lat: 43.2630, lng: -2.9350, zonas: ['Abando', 'Deusto', 'Indautxu', 'San Ignacio', 'Santutxu', 'Rekalde', 'Begoña'], contenidoLocal: {} },
  { slug: 'alicante', nombre: 'Alicante', comunidad: 'Comunitat Valenciana', poblacion: 337000, lat: 38.3452, lng: -0.4810, zonas: ['Centro', 'Playa de San Juan', 'Carolinas', 'Campoamor', 'San Blas', 'Altozano'], contenidoLocal: {} },
  { slug: 'murcia', nombre: 'Murcia', comunidad: 'Región de Murcia', poblacion: 460000, lat: 37.9922, lng: -1.1307, zonas: ['Centro', 'El Carmen', 'Infante Juan Manuel', 'San Andrés', 'Vistabella', 'La Flota'], contenidoLocal: {} },
  { slug: 'palma-de-mallorca', nombre: 'Palma de Mallorca', comunidad: 'Islas Baleares', poblacion: 420000, lat: 39.5696, lng: 2.6502, zonas: ['Centro', 'El Terreno', 'Son Espanyolet', 'Santa Catalina', 'El Molinar', 'Son Armadams'], contenidoLocal: {} },
  { slug: 'las-palmas', nombre: 'Las Palmas de Gran Canaria', comunidad: 'Canarias', poblacion: 380000, lat: 28.1235, lng: -15.4363, zonas: ['Vegueta', 'Triana', 'Ciudad Jardín', 'Guanarteme', 'Alcaravaneras', 'Mesa y López'], contenidoLocal: {} },
  { slug: 'valladolid', nombre: 'Valladolid', comunidad: 'Castilla y León', poblacion: 300000, lat: 41.6523, lng: -4.7245, zonas: ['Centro', 'Delicias', 'Parquesol', 'Huerta del Rey', 'La Victoria', 'Covaresa'], contenidoLocal: {} },
  { slug: 'cordoba', nombre: 'Córdoba', comunidad: 'Andalucía', poblacion: 325000, lat: 37.8882, lng: -4.7794, zonas: ['Centro', 'Levante', 'Poniente-Sur', 'Norte-Sierra', 'Fuensanta', 'Brillante'], contenidoLocal: {} },
  { slug: 'granada', nombre: 'Granada', comunidad: 'Andalucía', poblacion: 232000, lat: 37.1773, lng: -3.5986, zonas: ['Centro', 'Zaidín', 'Chana', 'Albaicín', 'Ronda', 'Genil', 'Beiro'], contenidoLocal: {} },
];

export function getCiudad(slug: string) {
  return CIUDADES.find((c) => c.slug === slug);
}

export function getCiudadSlugs() {
  return CIUDADES.map((c) => c.slug);
}
